spring:
  application:
    name: gateway
server:
  port: 9601
eureka:
  instance:
    hostname: gateway
  client:
    service-url:
      defaultZone: http://peer1:9001/eureka/,http://peer2:9002/eureka/

# 下面整个树都非必须，如果不配置，将默认使用 http://GATEWAY:GATEWAY_PORT/想要访问的Eureka服务id的小写/** 路由到：http://想要访问的Eureka服务id的小写:该服务端口/**
zuul:
  ignored-services: consumer-feign # 需要忽视的服务(配置后将不会被路由)
  routes:
    user: # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /user/** # 想要映射到的路径
      service-id: provide-user # Eureka中的serviceId
    feign:
      path: /ap2/**
      service-id: consumer-feign