server:
  port: 9301
spring:
  application:
    name: consumer-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://peer1:9001/eureka/,http://peer2:9002/eureka/
  instance:
    hostname: hystrix